### ISSUE TITLE
Can I help you Eng. Mohmed in this repo? I can search and collect some projects  for contributing in this project.

### ISSUE THREAD

**Issue by GAbdulWahab** [cs-MohamedAyman/Educational-Projects#1]

**Comment by GAbdulWahab** [comment]
@cs-MohamedAyman  ok , thank you

**Comment by cs-MohamedAyman** [comment]
I'm available today after 8 pm, when you be available please share with me a google meet link.

**Comment by GAbdulWahab** [comment]
hello, @cs-MohamedAyman  I am sorry for the late, but I'm busy now  I have a Midterm Exam Tomorrow, and can we talk on Thursday?

**Comment by cs-MohamedAyman** [comment]
Ok, sure.
